### ISSUE TITLE
Error while running pixel-nerf/train/train.py

### ISSUE THREAD

**Issue by iamankan** [abrilcf/mednerf#11]
Erro while running the train.py for pixel-nerf (The running command is:
python3 train.py --conf ../conf/exp/ct_single.conf)

``` /home/ankan/Documents/mednerf/gitfull/pixelnerfenv/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
pyparsing.exceptions.ParseException: Expected '}', found '='  (at char 759), (line:34, col:18)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ankan/Documents/mednerf/gitfull/mednerf/pixel-nerf/pixel-nerf/train/train.py", line 56, in <module>
    args, conf = util.args.parse_args(extra_args, training=True, default_ray_batch_size=128)
  File "/home/ankan/Documents/mednerf/gitfull/mednerf/pixel-nerf/pixel-nerf/src/util/args.py", line 99, in parse_args
    conf = ConfigFactory.parse_file(args.conf)
  File "/home/ankan/Documents/mednerf/gitfull/pixelnerfenv/lib/python3.10/site-packages/pyhocon/config_parser.py", line 142, in parse_file
    return cls.parse_string(content, os.path.dirname(filename), resolve, unresolved_value)
  File "/home/ankan/Documents/mednerf/gitfull/pixelnerfenv/lib/python3.10/site-packages/pyhocon/config_parser.py", line 192, in parse_string
    return ConfigParser().parse(content, basedir, resolve, unresolved_value)
  File "/home/ankan/Documents/mednerf/gitfull/pixelnerfenv/lib/python3.10/site-packages/pyhocon/config_parser.py", line 455, in parse
    config = config_expr.parseString(content, parseAll=True)[0]
  File "/home/ankan/Documents/mednerf/gitfull/pixelnerfenv/lib/python3.10/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseSyntaxException: Expected '}', found '='  (at char 759), (line:34, col:18)

**Comment by iamankan** [comment]
Put commas after every key-value pairs. Like this:
```
mlp_coarse {
        type = resnet, # Can change to resnet or siren
        n_blocks = 3,
        d_hidden = 512
    }
```
